<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--<Nullable>enable</Nullable>-->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Services.csproj" />
    <ProjectReference Include="..\Data\Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Controllers\" />
    <None Remove="Swashbuckle.AspNetCore" />
    <None Remove="Swashbuckle.AspNetCore.Annotations" />
    <None Remove="Models\" />
    <None Remove="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <None Remove="Microsoft.IdentityModel.Tokens" />
    <None Remove="System.IdentityModel.Tokens.Jwt" />
    <None Remove="Infragistics.Web.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Models\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.24.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.24.0" />
    <PackageReference Include="Infragistics.Web.AspNetCore" Version="6.22.1.8" />
  </ItemGroup>
</Project>
